---
name: CI

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        platform: ['iOS Simulator,name=iPhone 8']
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test
  analyze:
    name: Analyze
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: analyze
        run: make analyze
  cocoapods:
    name: CocoaPods
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: make cocoapods
  carthage:
    name: Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: carthage
        run: make carthage
